language: swift
xcode_workspace: ContactList.xcworkspace
xcode_scheme: ContactList
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 11
osx_image: xcode11.3
os: osx

branches:
  only: # safelist
  - master